Auth flow done
AndreiGS/PharmaKronsoft pull request #1
Opened 2022-11-23 21:18 UTC by AndreiGS

Users are able to register -> returns a pair of jwt and refresh token in their respective headers
Dev should be able to use C_ResponseEntity so the token refreshing happens automatically
New AuthProviders should be easy to use
Paths should be restricted to authenticated users
Endpoints should be able to use the ROLE_ authorizations

2022-11-25 07:08 UTC, mirela7 requested changes
+ Add comments (on security-related classes) (suggestions: add on `C_ResponseEntity`, `JWTAuthenticationToken`, `TokenUtil`, filters, `WebSecurityConfig`)

2022-11-25 07:08 UTC, mirela7 commented on backend/src/main/java/com/kronsoft/pharma/auth/role/exeption/NotRoleException.java
> +public class NotRoleException extends RuntimeException {
suggestion rename to `InvalidRoleException`

2022-11-28 15:05 UTC, AndreiGS commented on backend/src/main/java/com/kronsoft/pharma/auth/role/exeption/NotRoleException.java
> +public class NotRoleException extends RuntimeException {
Thank you for the feedback. In the last commit I have added comments on all specified classes, hope it looks more readable now :)

2022-11-28 16:19 UTC, mirela7 approved these changes

2022-11-28 16:29 UTC, merged